In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cross_validation,preprocessing
from sklearn.linear_model import LinearRegression

In [38]:
train = pd.read_csv("/home/shivam/Downloads/Data Science workshop/random-linear-regression/train.csv",sep=',')
train

       x           y
0     24   21.549452
1     50   47.464463
2     15   17.218656
3     38   36.586398
4     87   87.288984
5     36   32.463875
6     12   10.780897
7     81   80.763399
8     25   24.612151
9      5    6.963319
10    16   11.237573
11    16   13.532902
12    24   24.603239
13    39   39.400500
14    54   48.437538
15    60   61.699003
16    26   26.928324
17    73   70.405206
18    29   29.340924
19    31   25.308952
20    68   69.029343
21    87   84.994847
22    58   57.043103
23    54   50.592199
24    84   83.027722
25    58   57.057527
26    49   47.958833
27    20   24.342264
28    90   94.684883
29    48   48.039707
..   ...         ...
670   84   82.889358
671   64   63.613650
672   12   11.296272
673   61   60.022749
674   75   72.603393
675   15   11.879646
676  100  100.701274
677   43   45.124208
678   13   14.811068
679   48   48.093680
680   45   42.291457
681   52   52.733898
682   34   36.723970
683   30   28.645352
684   65   62.166753
685  100   95.584595
686   67   66.043253
687   99   99.956622
688   45   46.149420
689   87   89.137550
690   73   69.717878
691    9   12.317366
692   81   78.202963
693   72   71.309954
694   81   81.455447
695   58   58.595006
696   93   94.625094
697   82   88.603770
698   66   63.648685
699   97   94.975266

[700 rows x 2 columns]

In [39]:
train['x'].head()

0    24
1    50
2    15
3    38
4    87
Name: x, dtype: int64

In [68]:
# Here linear reg. is done by splitting a single train dataset into traing and testing sets.

X = np.array(train['x'])
y = np.array(train['y'])
#X = preprocessing.scale(X) # It is required when our dataset has multiple columns. At that time we need to scale it with the help of this function.
#y = np.array(train['y'])
X_train,X_test,y_train,y_test = cross_validation.train_test_split(X,y,test_size=0.2)
clf=LinearRegression()    #clf is the regression classifier
clf.fit(X_train.reshape(-1, 1),y_train)   #reshape to convert it from 1 dimentional array to 2D array.
accuracy = clf.score(X_test.reshape(-1, 1),y_test)
print accuracy

0.990216878216

In [40]:
test = pd.read_csv("/home/shivam/Downloads/Data Science workshop/random-linear-regression/test.csv",sep=',')
test

      x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
5    15   9.805235
6    62  58.874659
7    95  97.617937
8    20  18.395127
9     5   8.746748
10    4   2.811416
11   19  17.095372
12   96  95.149072
13   62  61.388007
14   36  40.247017
15   15  14.822486
16   65  66.958069
17   14  16.635080
18   87  90.655137
19   69  77.229826
20   89  92.119063
21   51  46.913877
22   89  89.826344
23   27  21.713803
24   97  97.412070
25   58  57.016314
26   79  78.310565
27   21  19.131510
28   93  93.034834
29   27  26.591124
..   ..        ...
270  55  55.816285
271   8   9.391417
272  56  56.014481
273  72  77.996948
274  58  55.370500
275   6  11.894578
276  96  94.790817
277  23  25.690415
278  58  53.520423
279  23  18.313968
280  19  21.426378
281  25  30.413033
282  64  67.681421
283  21  17.085478
284  59  60.917927
285  19  14.995143
286  16  16.749239
287  42  41.469239
288  43  42.845261
289  61  59.129130
290  92  91.308637
291  11   8.673336
292  41  39.314853
293   1   5.313686
294   8   5.405221
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]

In [58]:
# Without splitting a single dataset into test and train. Here we have 2 datasets involved i.e train dataset and test datset.
# X_Train,X_test,y_train,y_test all of them are assigned to a seperate column and then linear reg. is performed.

X_train = np.array(train['x'])
X_test = np.array(test['x'])
y_train = np.array(train['y'])
y_test = np.array(test['y'])
clf = LinearRegression()   #clf is the regression classifier.
clf.fit(X_train.reshape(-1,1),y_train)   #reshape to convert it from 1 dimentional array to 2D array.
accuracy = clf.score(X_test.reshape(-1, 1),y_test)
print accuracy

0.988796296081